"""Add rollup tables for MVP

Revision ID: 6419baa08b6c
Revises: 001
Create Date: 2025-09-12 23:30:31.088532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6419baa08b6c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('jwt_secret', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('devices_device_key_key'), 'devices', type_='unique')
    op.drop_index(op.f('ix_devices_device_key'), table_name='devices')
    op.create_index(op.f('ix_devices_device_key'), 'devices', ['device_key'], unique=True)
    op.create_index(op.f('ix_devices_jwt_secret'), 'devices', ['jwt_secret'], unique=False)
    
    # Create rollup tables for MVP (split commands for asyncpg compatibility)
    op.execute("""
        CREATE TABLE IF NOT EXISTS usage_1m (
            account_id TEXT NOT NULL,
            device_id TEXT NOT NULL,
            bucket_start TIMESTAMPTZ NOT NULL,
            kind TEXT NOT NULL,
            key TEXT NOT NULL,
            secs_sum DOUBLE PRECISION DEFAULT 0,
            events_count INTEGER DEFAULT 0,
            last_ts TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            PRIMARY KEY (account_id, device_id, bucket_start, kind, key)
        )
    """)
    
    op.execute("CREATE INDEX IF NOT EXISTS idx_usage_1m_lookup ON usage_1m (account_id, device_id, bucket_start DESC)")
    
    op.execute("""
        CREATE TABLE IF NOT EXISTS usage_5m (
            account_id TEXT NOT NULL,
            device_id TEXT NOT NULL,
            bucket_start TIMESTAMPTZ NOT NULL,
            kind TEXT NOT NULL,
            key TEXT NOT NULL,
            secs_sum DOUBLE PRECISION DEFAULT 0,
            events_count INTEGER DEFAULT 0,
            last_ts TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            PRIMARY KEY (account_id, device_id, bucket_start, kind, key)
        )
    """)
    
    op.execute("CREATE INDEX IF NOT EXISTS idx_usage_5m_lookup ON usage_5m (account_id, device_id, bucket_start DESC)")
    
    op.execute("""
        CREATE TABLE IF NOT EXISTS usage_60m (
            account_id TEXT NOT NULL,
            device_id TEXT NOT NULL,
            bucket_start TIMESTAMPTZ NOT NULL,
            kind TEXT NOT NULL,
            key TEXT NOT NULL,
            secs_sum DOUBLE PRECISION DEFAULT 0,
            events_count INTEGER DEFAULT 0,
            last_ts TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            PRIMARY KEY (account_id, device_id, bucket_start, kind, key)
        )
    """)
    
    op.execute("CREATE INDEX IF NOT EXISTS idx_usage_60m_lookup ON usage_60m (account_id, device_id, bucket_start DESC)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_jwt_secret'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_key'), table_name='devices')
    op.create_index(op.f('ix_devices_device_key'), 'devices', ['device_key'], unique=False)
    op.create_unique_constraint(op.f('devices_device_key_key'), 'devices', ['device_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('devices', 'last_heartbeat_at')
    op.drop_column('devices', 'jwt_secret')
    # ### end Alembic commands ###
